# Generated by Django 5.2.4 on 2025-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='alt_recipe',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='original_recipe',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
