# Generated by Django 5.2.4 on 2025-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_remove_dish_alt_recipe_remove_dish_original_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/dish/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/ingredient/'),
        ),
    ]
