# Generated by Django 5.2.4 on 2025-08-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_dish_instructions_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
